### ISSUE TITLE
Could not find config.proto or config_pb2 for abstract generator

### ISSUE THREAD

**Issue by justinbabu** [JSybrandt/agatha#11]
Hi,

I was trying to  run this repo but could not find the config file (python class or proto). Hope you can add it.

_abstract_generator/generation_util.py", line 4, in <module>
from agatha.config import config_pb2 as cpb
ModuleNotFoundError: No module named 'agatha.config'_

**Comment by JSybrandt** [comment]
Please run `make` in the root directory of this project in order to build the proto specs.

Additionally, I'm in the middle of resolving incompatibilities surrounding the abstract generation module. We're in the middle of some significant refactoring. 

If you would like to reference the CBAG model, please take a look at `https://github.com/JSybrandt/agatha/releases`   There you can find a prior snapshot of the codebase with a functional abstract generator. Otherwise, we should have the incompatibilities resolved in the next couple of weeks.
